// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: command/command.proto

package io.net.api.command;

public final class CommandProto {
  private CommandProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
      String[] descriptorData = {
              "\n\025command/command.proto\022\020protobuf.comman" +
                      "d\032\nbase.proto24\n\017GroupCmdService\022!\n\006invo" +
                      "ke\022\t.GroupCmd\032\n.MsgResult\"\000B\'\n\022io.net.ap" +
                      "i.commandB\014CommandProtoP\001\240\001\001b\006proto3"
      };
      descriptor = com.google.protobuf.Descriptors.FileDescriptor
              .internalBuildGeneratedFileFrom(descriptorData,
                      new com.google.protobuf.Descriptors.FileDescriptor[]{
                              io.net.api.BaseProto.getDescriptor(),
                      });
      io.net.api.BaseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
