// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: command/command.proto

package io.net.api.command;

public interface GroupCmdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.command.GroupCmd)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 groupId = 1;</code>
   * @return The groupId.
   */
  long getGroupId();

  /**
   * <code>uint64 botId = 2;</code>
   * @return The botId.
   */
  long getBotId();

  /**
   * <code>uint64 senderId = 3;</code>
   * @return The senderId.
   */
  long getSenderId();

  /**
   * <code>string cmd = 4;</code>
   * @return The cmd.
   */
  String getCmd();
  /**
   * <code>string cmd = 4;</code>
   * @return The bytes for cmd.
   */
  com.google.protobuf.ByteString
      getCmdBytes();

  /**
   * <code>repeated string args = 5;</code>
   * @return A list containing the args.
   */
  java.util.List<String>
      getArgsList();
  /**
   * <code>repeated string args = 5;</code>
   * @return The count of args.
   */
  int getArgsCount();
  /**
   * <code>repeated string args = 5;</code>
   * @param index The index of the element to return.
   * @return The args at the given index.
   */
  String getArgs(int index);
  /**
   * <code>repeated string args = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the args at the given index.
   */
  com.google.protobuf.ByteString
      getArgsBytes(int index);
}
