// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: command/command.proto

package io.net.api.command;

public interface MsgResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.command.MsgResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msg = 1;</code>
   * @return The msg.
   */
  String getMsg();
  /**
   * <code>string msg = 1;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>bytes bytes = 2;</code>
   * @return The bytes.
   */
  com.google.protobuf.ByteString getBytes();
}
