version: "3.8"

services:
  qsign:
    image: xzhouqd/qsign:core-1.1.5
    container_name: qsign-dev
    environment:
      - BASE_PATH=/srv/qsign/qsign/txlib/8.9.63
    healthcheck:
      test: [ "CMD-SHELL", "curl -sS 'http://localhost' || exit 1" ]
      interval: 30s
      timeout: 20s
      retries: 5
    ports:
      - "8080:8080"
    restart: on-failure
  postgresql:
    image: postgres
    container_name: postgresql-dev
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=service
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgresql_dev:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: on-failure
  zookeeper:
    image: zookeeper
    container_name: zookeeper-dev
    restart: on-failure
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
  minio:
    image: minio/minio
    container_name: minio-dev
    volumes:
      - minio_dev:/mnt/data
    ports:
      - "9000:9000"
      - "9090:9090"
    restart: on-failure
    command: server --console-address ":9090" /mnt/data

volumes:
  postgresql_dev:
  minio_dev: