
spring:
  application:
    name: service-command
dubbo:
  application:
    name: ${spring.application.name}
    qos-port: 60002
  protocol:
    id: tri
    name: tri
    port: -1
  registry:
    address: nacos://localhost:8848
  metadata-report:
    address: nacos://localhost:8848
logging:
  pattern:
    dateformat: yyyy-MM-dd hh:mm:ss.SSS
cmd:
  name: "augenstern-bot"
  version: "3.0.0"
  powered-by: "mirai | spring | dubbo"
  sudo: [ 1307083930, 5971 ]
  permission:
    666:
      - gpt
      - img
      - st
      - steam
    474270623:
      - gpt
      - img
      - st
      - steam
    1053148332:
      - gpt
      - img
      - st
      - steam