dubbo:
  registry:
    address: zookeeper://zookeeper:2181
  metadata-report:
    address: zookeeper://zookeeper:2181
logging:
  level:
    root: error
    io.net.command.*: info
  file:
    name: ./logger.log