app:
  pixiv-r18-recall-in: 35s
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/service
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
dubbo:
  registry:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181
logging:
  level:
    sql: debug
minio:
  host: localhost
  port: 9000
  accessKey: minioadmin
  secretKey: minioadmin
proxy:
  host: localhost
  port: 62495