spring:
  application:
    name: service-image
dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
  config-center:
    address: nacos://localhost:8848
  metadata-report:
    address: nacos://localhost:8848