spring:
  application:
    name: service-image
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/service
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  protocol:
    id: tri
    name: tri
    port: -1
  registry:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181
logging:
  pattern:
    dateformat: yyyy-MM-dd hh:mm:ss.SSS
minio:
  host: localhost
  port: 9000
  accessKey: minioadmin
  secretKey: minioadmin
rest:
  host: localhost
  port: 62495