spring:
  application:
    name: service-image
  profiles:
    active: dev
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  protocol:
    id: tri
    name: tri
    port: -1
logging:
  pattern:
    dateformat: yyyy-MM-dd hh:mm:ss.SSS