spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/service
dubbo:
  registry:
    address: zookeeper://zookeeper:2181
  metadata-report:
    address: zookeeper://zookeeper:2181
logging:
  level:
    root: error
    sql: off
    io.net.image.*: info
  file:
    name: ./logger.log
minio:
  host: minio
proxy:
  host: clash
  port: 7890