spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/service
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
  data:
    redis:
      host: redis
      port: 6379
      database: 0
dubbo:
  registry:
    address: zookeeper://zookeeper:2181
  metadata-report:
    address: zookeeper://zookeeper:2181
logging:
  level:
    root: error
    sql: off
    io.net.image.*: info
  file:
    name: ./logger.log
minio:
  host: minio
proxy:
  host: clash
  port: 7890
app:
  pixiv-r18-recall-in: 35s