// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: work/work.proto

package io.net.api.work;

public interface MenuOrBuilder extends
        // @@protoc_insertion_point(interface_extends:protobuf.work.Menu)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, string&gt; menu = 1;</code>
     */
    int getMenuCount();

    /**
     * <code>map&lt;string, string&gt; menu = 1;</code>
     */
    boolean containsMenu(
            String key);

    /**
     * Use {@link #getMenuMap()} instead.
     */
    @Deprecated
    java.util.Map<String, String>
    getMenu();

    /**
     * <code>map&lt;string, string&gt; menu = 1;</code>
     */
    java.util.Map<String, String>
    getMenuMap();

    /**
     * <code>map&lt;string, string&gt; menu = 1;</code>
     */

    String getMenuOrDefault(
            String key,
            String defaultValue);

    /**
     * <code>map&lt;string, string&gt; menu = 1;</code>
     */

    String getMenuOrThrow(
            String key);
}
