// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: work/work.proto

package io.net.api.work;

public interface MenuOrBuilder extends
        // @@protoc_insertion_point(interface_extends:protobuf.work.Menu)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, string&gt; menu = 1;</code>
     */
    int getMenuCount();

    /**
     * <code>map&lt;string, string&gt; menu = 1;</code>
     */
    boolean containsMenu(
            java.lang.String key);

    /**
     * Use {@link #getMenuMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getMenu();

    /**
     * <code>map&lt;string, string&gt; menu = 1;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getMenuMap();

    /**
     * <code>map&lt;string, string&gt; menu = 1;</code>
     */

    java.lang.String getMenuOrDefault(
            java.lang.String key,
            java.lang.String defaultValue);

    /**
     * <code>map&lt;string, string&gt; menu = 1;</code>
     */

    java.lang.String getMenuOrThrow(
            java.lang.String key);
}
