spring:
  application:
    name: bot
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  protocol:
    id: tri
    name: tri
    port: -1
  registry:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181
logging:
  pattern:
    dateformat: yyyy-MM-dd hh:mm:ss.SSS
  level:
    net.mamoe.mirai.*: trace