spring:
  application:
    name: bot
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  protocol:
    id: tri
    name: tri
  registry:
    address: nacos://localhost:8848
  config-center:
    address: nacos://localhost:8848
  metadata-report:
    address: nacos://localhost:8848
logging:
  level:
    net.mamoe.mirai.*: trace