spring:
  application:
    name: bot
  profiles:
    active: dev
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  protocol:
    id: tri
    name: tri
    port: -1
logging:
  pattern:
    dateformat: yyyy-MM-dd hh:mm:ss.SSS