spring:
  application:
    name: service-text
  profiles:
    active: dev
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  protocol:
    id: tri
    name: tri
    port: -1
logging:
  pattern:
    dateformat: yyyy-MM-dd hh:mm:ss.SSS