app:
  openai-api-key: ""
dubbo:
  registry:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181
logging:
  level:
    web: debug
proxy:
  host: localhost
  port: 62495