// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

package io.net.api;

public final class BaseProto {
  private BaseProto() {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
          internal_static_GroupCmd_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_GroupCmd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
          internal_static_MsgResultChain_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_MsgResultChain_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
          internal_static_MsgResultChain_MetaEntry_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_MsgResultChain_MetaEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
          internal_static_MsgResultChain_Receipt_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_MsgResultChain_Receipt_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
          internal_static_MsgResult_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_MsgResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
          internal_static_MsgResult_Data_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_MsgResult_Data_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor
          descriptor;

  static {
    String[] descriptorData = {
            "\n\nbase.proto\"d\n\010GroupCmd\022\013\n\003ats\030\001 \003(\004\022\017\n" +
                    "\007groupId\030\002 \001(\004\022\r\n\005botId\030\003 \001(\004\022\020\n\010senderI" +
                    "d\030\004 \001(\004\022\013\n\003cmd\030\005 \001(\t\022\014\n\004args\030\006 \003(\t\"\267\002\n\016M" +
                    "sgResultChain\022\"\n\004code\030\001 \001(\0162\024.MsgResultC" +
                    "hain.Code\022\035\n\tmsgResult\030\002 \003(\0132\n.MsgResult" +
                    "\022(\n\007receipt\030\003 \001(\0132\027.MsgResultChain.Recei" +
                    "pt\022\'\n\004meta\030\004 \003(\0132\031.MsgResultChain.MetaEn" +
                    "try\032+\n\tMetaEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002" +
                    " \001(\t:\0028\001\032+\n\007Receipt\022\016\n\006recall\030\001 \001(\005\022\020\n\010f" +
                    "allback\030\002 \001(\t\"5\n\004Code\022\006\n\002OK\020\000\022\024\n\020BUSINES" +
                    "S_ANOMALY\020\001\022\017\n\013RPC_ANOMALY\020\002\"\234\001\n\tMsgResu" +
                    "lt\022\013\n\003msg\030\001 \001(\t\022\035\n\004data\030\002 \001(\0132\017.MsgResul" +
                    "t.Data\032c\n\004Data\022\'\n\004type\030\001 \001(\0162\031.MsgResult" +
                    ".Data.MediaType\022\r\n\005bytes\030\002 \001(\014\"#\n\tMediaT" +
                    "ype\022\013\n\007PICTURE\020\000\022\t\n\005AUDIO\020\001B\034\n\nio.net.ap" +
                    "iB\tBaseProtoP\001\240\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[]{
                    });
    internal_static_GroupCmd_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_GroupCmd_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_GroupCmd_descriptor,
            new String[]{"Ats", "GroupId", "BotId", "SenderId", "Cmd", "Args",});
    internal_static_MsgResultChain_descriptor =
            getDescriptor().getMessageTypes().get(1);
    internal_static_MsgResultChain_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_MsgResultChain_descriptor,
            new String[]{"Code", "MsgResult", "Receipt", "Meta",});
    internal_static_MsgResultChain_MetaEntry_descriptor =
            internal_static_MsgResultChain_descriptor.getNestedTypes().get(0);
    internal_static_MsgResultChain_MetaEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_MsgResultChain_MetaEntry_descriptor,
            new String[]{"Key", "Value",});
    internal_static_MsgResultChain_Receipt_descriptor =
            internal_static_MsgResultChain_descriptor.getNestedTypes().get(1);
    internal_static_MsgResultChain_Receipt_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_MsgResultChain_Receipt_descriptor,
            new String[]{"Recall", "Fallback",});
    internal_static_MsgResult_descriptor =
            getDescriptor().getMessageTypes().get(2);
    internal_static_MsgResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_MsgResult_descriptor,
            new String[]{"Msg", "Data",});
    internal_static_MsgResult_Data_descriptor =
            internal_static_MsgResult_descriptor.getNestedTypes().get(0);
    internal_static_MsgResult_Data_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_MsgResult_Data_descriptor,
            new String[]{"Type", "Bytes",});
  }

  // @@protoc_insertion_point(outer_class_scope)
}
