// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

package io.net.api;

public final class BaseProto {
    private BaseProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_GroupCmd_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_GroupCmd_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_MsgResult_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_MsgResult_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\nbase.proto\"W\n\010GroupCmd\022\017\n\007groupId\030\001 \001(" +
                        "\004\022\r\n\005botId\030\002 \001(\004\022\020\n\010senderId\030\003 \001(\004\022\013\n\003cm" +
                        "d\030\004 \001(\t\022\014\n\004args\030\005 \003(\t\"C\n\tMsgResult\022\014\n\004co" +
                        "de\030\001 \001(\005\022\013\n\003msg\030\002 \001(\t\022\r\n\005bytes\030\003 \001(\014\022\014\n\004" +
                        "foot\030\004 \001(\tB\"\n\nio.net.apiB\tBaseProtoP\001\240\001\001" +
                        "\242\002\003DSPb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_GroupCmd_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_GroupCmd_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_GroupCmd_descriptor,
                new java.lang.String[]{"GroupId", "BotId", "SenderId", "Cmd", "Args",});
        internal_static_MsgResult_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_MsgResult_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_MsgResult_descriptor,
                new java.lang.String[]{"Code", "Msg", "Bytes", "Foot",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
