// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

package io.net.api;

/**
 * Protobuf enum {@code MsgCode}
 */
public enum MsgCode
        implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>OK = 0;</code>
     */
    OK(0),
    /**
     * <code>BUSINESS_ANOMALY = 1;</code>
     */
    BUSINESS_ANOMALY(1),
    /**
     * <code>RPC_ANOMALY = 2;</code>
     */
    RPC_ANOMALY(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>OK = 0;</code>
     */
    public static final int OK_VALUE = 0;
    /**
     * <code>BUSINESS_ANOMALY = 1;</code>
     */
    public static final int BUSINESS_ANOMALY_VALUE = 1;
    /**
     * <code>RPC_ANOMALY = 2;</code>
     */
    public static final int RPC_ANOMALY_VALUE = 2;


    public final int getNumber() {
        if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalArgumentException(
                    "Can't get the number of an unknown enum value.");
        }
        return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgCode valueOf(int value) {
        return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MsgCode forNumber(int value) {
        switch (value) {
            case 0:
                return OK;
            case 1:
                return BUSINESS_ANOMALY;
            case 2:
                return RPC_ANOMALY;
            default:
                return null;
        }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgCode>
    internalGetValueMap() {
        return internalValueMap;
    }

    private static final com.google.protobuf.Internal.EnumLiteMap<
            MsgCode> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgCode>() {
                public MsgCode findValueByNumber(int number) {
                    return MsgCode.forNumber(number);
                }
            };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
    getValueDescriptor() {
        if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalStateException(
                    "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
    }

    public final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptorForType() {
        return getDescriptor();
    }

    public static final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptor() {
        return io.net.api.BaseProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final MsgCode[] VALUES = values();

    public static MsgCode valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
                    "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
            return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
    }

    private final int value;

    private MsgCode(int value) {
        this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MsgCode)
}

