// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

package io.net.api;

public interface MsgResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MsgResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.MsgCode code = 1;</code>
   * @return The enum numeric value on the wire for code.
   */
  int getCodeValue();
  /**
   * <code>.MsgCode code = 1;</code>
   * @return The code.
   */
  io.net.api.MsgCode getCode();

  /**
   * <code>string msg = 2;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 2;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>bytes bytes = 3;</code>
   * @return The bytes.
   */
  com.google.protobuf.ByteString getBytes();

  /**
   * <code>string foot = 4;</code>
   * @return The foot.
   */
  java.lang.String getFoot();
  /**
   * <code>string foot = 4;</code>
   * @return The bytes for foot.
   */
  com.google.protobuf.ByteString
      getFootBytes();
}
