// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

package io.net.api;

/**
 * Protobuf type {@code MsgResult}
 */
public final class MsgResult extends
    com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:MsgResult)
    MsgResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MsgResult.newBuilder() to construct.
  private MsgResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MsgResult() {
      code_ = 0;
      msg_ = "";
      bytes_ = com.google.protobuf.ByteString.EMPTY;
      foot_ = "";
  }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new MsgResult();
    }

    @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MsgResult(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
            case 0:
                done = true;
                break;
            case 8: {
                int rawValue = input.readEnum();

                code_ = rawValue;
                break;
            }
            case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                msg_ = s;
                break;
            }
            case 26: {

                bytes_ = input.readBytes();
                break;
            }
            case 34: {
                java.lang.String s = input.readStringRequireUtf8();

                foot_ = s;
                break;
            }
            default: {
                if (!parseUnknownField(
                        input, unknownFields, extensionRegistry, tag)) {
                    done = true;
                }
                break;
            }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
    }
  }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return io.net.api.BaseProto.internal_static_MsgResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return io.net.api.BaseProto.internal_static_MsgResult_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        io.net.api.MsgResult.class, io.net.api.MsgResult.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;

    /**
     * <code>.MsgCode code = 1;</code>
     *
     * @return The enum numeric value on the wire for code.
     */
    @java.lang.Override
    public int getCodeValue() {
        return code_;
    }

    /**
     * <code>.MsgCode code = 1;</code>
     *
     * @return The code.
     */
    @java.lang.Override
    public io.net.api.MsgCode getCode() {
        @SuppressWarnings("deprecation")
        io.net.api.MsgCode result = io.net.api.MsgCode.valueOf(code_);
        return result == null ? io.net.api.MsgCode.UNRECOGNIZED : result;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object msg_;

    /**
     * <code>string msg = 2;</code>
     *
     * @return The msg.
     */
    @java.lang.Override
    public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            msg_ = s;
            return s;
        }
    }

    /**
     * <code>string msg = 2;</code>
     *
     * @return The bytes for msg.
     */
  @java.lang.Override
  public com.google.protobuf.ByteString
  getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          msg_ = b;
          return b;
      } else {
          return (com.google.protobuf.ByteString) ref;
      }
  }

    public static final int BYTES_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString bytes_;

    /**
     * <code>bytes bytes = 3;</code>
     *
     * @return The bytes.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBytes() {
        return bytes_;
    }

    public static final int FOOT_FIELD_NUMBER = 4;
    private volatile java.lang.Object foot_;

    /**
     * <code>string foot = 4;</code>
     *
     * @return The foot.
     */
    @java.lang.Override
    public java.lang.String getFoot() {
        java.lang.Object ref = foot_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            foot_ = s;
            return s;
        }
    }

    /**
     * <code>string foot = 4;</code>
     *
     * @return The bytes for foot.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getFootBytes() {
        java.lang.Object ref = foot_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            foot_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
          throws java.io.IOException {
      if (code_ != io.net.api.MsgCode.OK.getNumber()) {
          output.writeEnum(1, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
      }
      if (!bytes_.isEmpty()) {
          output.writeBytes(3, bytes_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(foot_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 4, foot_);
      }
      unknownFields.writeTo(output);
  }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (code_ != io.net.api.MsgCode.OK.getNumber()) {
            size += com.google.protobuf.CodedOutputStream
                    .computeEnumSize(1, code_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
        }
        if (!bytes_.isEmpty()) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBytesSize(3, bytes_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(foot_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, foot_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof io.net.api.MsgResult)) {
            return super.equals(obj);
        }
        io.net.api.MsgResult other = (io.net.api.MsgResult) obj;

        if (code_ != other.code_) return false;
        if (!getMsg()
                .equals(other.getMsg())) return false;
        if (!getBytes()
                .equals(other.getBytes())) return false;
        if (!getFoot()
                .equals(other.getFoot())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + code_;
        hash = (37 * hash) + MSG_FIELD_NUMBER;
        hash = (53 * hash) + getMsg().hashCode();
        hash = (37 * hash) + BYTES_FIELD_NUMBER;
        hash = (53 * hash) + getBytes().hashCode();
        hash = (37 * hash) + FOOT_FIELD_NUMBER;
        hash = (53 * hash) + getFoot().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static io.net.api.MsgResult parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static io.net.api.MsgResult parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static io.net.api.MsgResult parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static io.net.api.MsgResult parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static io.net.api.MsgResult parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static io.net.api.MsgResult parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static io.net.api.MsgResult parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static io.net.api.MsgResult parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static io.net.api.MsgResult parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static io.net.api.MsgResult parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static io.net.api.MsgResult parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static io.net.api.MsgResult parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(io.net.api.MsgResult prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code MsgResult}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:MsgResult)
            io.net.api.MsgResultOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return io.net.api.BaseProto.internal_static_MsgResult_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return io.net.api.BaseProto.internal_static_MsgResult_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            io.net.api.MsgResult.class, io.net.api.MsgResult.Builder.class);
        }

        // Construct using io.net.api.MsgResult.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            code_ = 0;

            msg_ = "";

            bytes_ = com.google.protobuf.ByteString.EMPTY;

            foot_ = "";

            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return io.net.api.BaseProto.internal_static_MsgResult_descriptor;
        }

        @java.lang.Override
        public io.net.api.MsgResult getDefaultInstanceForType() {
            return io.net.api.MsgResult.getDefaultInstance();
        }

        @java.lang.Override
        public io.net.api.MsgResult build() {
            io.net.api.MsgResult result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public io.net.api.MsgResult buildPartial() {
            io.net.api.MsgResult result = new io.net.api.MsgResult(this);
            result.code_ = code_;
            result.msg_ = msg_;
            result.bytes_ = bytes_;
            result.foot_ = foot_;
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof io.net.api.MsgResult) {
                return mergeFrom((io.net.api.MsgResult) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(io.net.api.MsgResult other) {
            if (other == io.net.api.MsgResult.getDefaultInstance()) return this;
            if (other.code_ != 0) {
                setCodeValue(other.getCodeValue());
            }
            if (!other.getMsg().isEmpty()) {
                msg_ = other.msg_;
                onChanged();
            }
            if (other.getBytes() != com.google.protobuf.ByteString.EMPTY) {
                setBytes(other.getBytes());
            }
            if (!other.getFoot().isEmpty()) {
                foot_ = other.foot_;
                onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

        @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.net.api.MsgResult parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.net.api.MsgResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
      } finally {
          if (parsedMessage != null) {
              mergeFrom(parsedMessage);
          }
      }
        return this;
    }

        private int code_ = 0;

        /**
         * <code>.MsgCode code = 1;</code>
         *
         * @return The enum numeric value on the wire for code.
         */
        @java.lang.Override
        public int getCodeValue() {
            return code_;
        }

        /**
         * <code>.MsgCode code = 1;</code>
         *
         * @param value The enum numeric value on the wire for code to set.
         * @return This builder for chaining.
         */
        public Builder setCodeValue(int value) {

            code_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>.MsgCode code = 1;</code>
         *
         * @return The code.
         */
        @java.lang.Override
        public io.net.api.MsgCode getCode() {
            @SuppressWarnings("deprecation")
            io.net.api.MsgCode result = io.net.api.MsgCode.valueOf(code_);
            return result == null ? io.net.api.MsgCode.UNRECOGNIZED : result;
        }

        /**
         * <code>.MsgCode code = 1;</code>
         *
         * @param value The code to set.
         * @return This builder for chaining.
         */
        public Builder setCode(io.net.api.MsgCode value) {
            if (value == null) {
                throw new NullPointerException();
            }

            code_ = value.getNumber();
            onChanged();
            return this;
        }

        /**
         * <code>.MsgCode code = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearCode() {

            code_ = 0;
            onChanged();
            return this;
        }

        private java.lang.Object msg_ = "";

        /**
         * <code>string msg = 2;</code>
         *
         * @return The msg.
         */
        public java.lang.String getMsg() {
            java.lang.Object ref = msg_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                msg_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string msg = 2;</code>
         *
         * @return The bytes for msg.
         */
        public com.google.protobuf.ByteString
        getMsgBytes() {
            java.lang.Object ref = msg_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                msg_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string msg = 2;</code>
         *
         * @param value The msg to set.
         * @return This builder for chaining.
         */
        public Builder setMsg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

            msg_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string msg = 2;</code>
         * @return This builder for chaining.
     */
    public Builder clearMsg() {
      
      msg_ = getDefaultInstance().getMsg();
      onChanged();
      return this;
    }
    /**
     * <code>string msg = 2;</code>
     * @param value The bytes for msg to set.
     * @return This builder for chaining.
     */
    public Builder setMsgBytes(
        com.google.protobuf.ByteString value) {
        if (value == null) {
            throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);
      
      msg_ = value;
      onChanged();
      return this;
    }

        private com.google.protobuf.ByteString bytes_ = com.google.protobuf.ByteString.EMPTY;

        /**
         * <code>bytes bytes = 3;</code>
     * @return The bytes.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBytes() {
      return bytes_;
    }
    /**
     * <code>bytes bytes = 3;</code>
     * @param value The bytes to set.
     * @return This builder for chaining.
     */
    public Builder setBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
            throw new NullPointerException();
        }

        bytes_ = value;
        onChanged();
        return this;
    }

        /**
         * <code>bytes bytes = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearBytes() {

            bytes_ = getDefaultInstance().getBytes();
            onChanged();
            return this;
        }

        private java.lang.Object foot_ = "";

        /**
         * <code>string foot = 4;</code>
         *
         * @return The foot.
         */
        public java.lang.String getFoot() {
            java.lang.Object ref = foot_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                foot_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string foot = 4;</code>
         *
         * @return The bytes for foot.
         */
        public com.google.protobuf.ByteString
        getFootBytes() {
            java.lang.Object ref = foot_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                foot_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string foot = 4;</code>
         *
         * @param value The foot to set.
         * @return This builder for chaining.
         */
        public Builder setFoot(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            foot_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string foot = 4;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearFoot() {

            foot_ = getDefaultInstance().getFoot();
            onChanged();
            return this;
        }

        /**
         * <code>string foot = 4;</code>
         *
         * @param value The bytes for foot to set.
         * @return This builder for chaining.
         */
        public Builder setFootBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            foot_ = value;
            onChanged();
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:MsgResult)
    }

    // @@protoc_insertion_point(class_scope:MsgResult)
    private static final io.net.api.MsgResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.net.api.MsgResult();
  }

  public static io.net.api.MsgResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MsgResult>
          PARSER = new com.google.protobuf.AbstractParser<MsgResult>() {
      @java.lang.Override
      public MsgResult parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
      return new MsgResult(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MsgResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MsgResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.net.api.MsgResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

