// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

package io.net.api;

/**
 * Protobuf type {@code MsgResultChain}
 */
public final class MsgResultChain extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:MsgResultChain)
        MsgResultChainOrBuilder {
  private static final long serialVersionUID = 0L;

  // Use MsgResultChain.newBuilder() to construct.
  private MsgResultChain(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private MsgResultChain() {
    code_ = 0;
    msgResult_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
          UnusedPrivateParameter unused) {
    return new MsgResultChain();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }

  private MsgResultChain(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            code_ = rawValue;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              msgResult_ = new java.util.ArrayList<MsgResult>();
              mutable_bitField0_ |= 0x00000001;
            }
            msgResult_.add(
                    input.readMessage(MsgResult.parser(), extensionRegistry));
            break;
          }
          case 26: {
            Receipt.Builder subBuilder = null;
            if (receipt_ != null) {
              subBuilder = receipt_.toBuilder();
            }
            receipt_ = input.readMessage(Receipt.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(receipt_);
              receipt_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              meta_ = com.google.protobuf.MapField.newMapField(
                      MetaDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<String, String>
                    meta__ = input.readMessage(
                    MetaDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            meta_.getMutableMap().put(
                    meta__.getKey(), meta__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        msgResult_ = java.util.Collections.unmodifiableList(msgResult_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return BaseProto.internal_static_MsgResultChain_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @Override
  protected com.google.protobuf.MapField internalGetMapField(
          int number) {
    switch (number) {
      case 4:
        return internalGetMeta();
      default:
        throw new RuntimeException(
                "Invalid map field number: " + number);
    }
  }

  @Override
  protected FieldAccessorTable
  internalGetFieldAccessorTable() {
    return BaseProto.internal_static_MsgResultChain_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    MsgResultChain.class, Builder.class);
  }

  /**
   * Protobuf enum {@code MsgResultChain.Code}
   */
  public enum Code
          implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>OK = 0;</code>
     */
    OK(0),
    /**
     * <code>BUSINESS_ANOMALY = 1;</code>
     */
    BUSINESS_ANOMALY(1),
    /**
     * <code>RPC_ANOMALY = 2;</code>
     */
    RPC_ANOMALY(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>OK = 0;</code>
     */
    public static final int OK_VALUE = 0;
    /**
     * <code>BUSINESS_ANOMALY = 1;</code>
     */
    public static final int BUSINESS_ANOMALY_VALUE = 1;
    /**
     * <code>RPC_ANOMALY = 2;</code>
     */
    public static final int RPC_ANOMALY_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
                "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Code valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Code forNumber(int value) {
      switch (value) {
        case 0:
          return OK;
        case 1:
          return BUSINESS_ANOMALY;
        case 2:
          return RPC_ANOMALY;
        default:
          return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Code>
    internalGetValueMap() {
      return internalValueMap;
    }

    private static final com.google.protobuf.Internal.EnumLiteMap<
            Code> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Code>() {
              public Code findValueByNumber(int number) {
                return Code.forNumber(number);
              }
            };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
    getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
                "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }

    public final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptorForType() {
      return getDescriptor();
    }

    public static final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptor() {
      return MsgResultChain.getDescriptor().getEnumTypes().get(0);
    }

    private static final Code[] VALUES = values();

    public static Code valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
                "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Code(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MsgResultChain.Code)
  }

  public interface ReceiptOrBuilder extends
          // @@protoc_insertion_point(interface_extends:MsgResultChain.Receipt)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 recall = 1;</code>
     *
     * @return The recall.
     */
    int getRecall();

    /**
     * <code>string fallback = 2;</code>
     *
     * @return The fallback.
     */
    String getFallback();

    /**
     * <code>string fallback = 2;</code>
     *
     * @return The bytes for fallback.
     */
    com.google.protobuf.ByteString
    getFallbackBytes();
  }

  /**
   * Protobuf type {@code MsgResultChain.Receipt}
   */
  public static final class Receipt extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:MsgResultChain.Receipt)
          ReceiptOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use Receipt.newBuilder() to construct.
    private Receipt(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private Receipt() {
      fallback_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
            UnusedPrivateParameter unused) {
      return new Receipt();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }

    private Receipt(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              recall_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              fallback_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                      input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return BaseProto.internal_static_MsgResultChain_Receipt_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
      return BaseProto.internal_static_MsgResultChain_Receipt_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      Receipt.class, Builder.class);
    }

    public static final int RECALL_FIELD_NUMBER = 1;
    private int recall_;

    /**
     * <code>int32 recall = 1;</code>
     *
     * @return The recall.
     */
    @Override
    public int getRecall() {
      return recall_;
    }

    public static final int FALLBACK_FIELD_NUMBER = 2;
    private volatile Object fallback_;

    /**
     * <code>string fallback = 2;</code>
     *
     * @return The fallback.
     */
    @Override
    public String getFallback() {
      Object ref = fallback_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fallback_ = s;
        return s;
      }
    }

    /**
     * <code>string fallback = 2;</code>
     *
     * @return The bytes for fallback.
     */
    @Override
    public com.google.protobuf.ByteString
    getFallbackBytes() {
      Object ref = fallback_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        fallback_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;

    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (recall_ != 0) {
        output.writeInt32(1, recall_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fallback_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fallback_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (recall_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(1, recall_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fallback_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fallback_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof Receipt)) {
        return super.equals(obj);
      }
      Receipt other = (Receipt) obj;

      if (getRecall()
              != other.getRecall()) return false;
      if (!getFallback()
              .equals(other.getFallback())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RECALL_FIELD_NUMBER;
      hash = (53 * hash) + getRecall();
      hash = (37 * hash) + FALLBACK_FIELD_NUMBER;
      hash = (53 * hash) + getFallback().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Receipt parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static Receipt parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Receipt parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static Receipt parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Receipt parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static Receipt parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Receipt parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static Receipt parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Receipt parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }

    public static Receipt parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static Receipt parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static Receipt parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(Receipt prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code MsgResultChain.Receipt}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:MsgResultChain.Receipt)
            ReceiptOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return BaseProto.internal_static_MsgResultChain_Receipt_descriptor;
      }

      @Override
      protected FieldAccessorTable
      internalGetFieldAccessorTable() {
        return BaseProto.internal_static_MsgResultChain_Receipt_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        Receipt.class, Builder.class);
      }

      // Construct using io.net.api.MsgResultChain.Receipt.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }

      @Override
      public Builder clear() {
        super.clear();
        recall_ = 0;

        fallback_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return BaseProto.internal_static_MsgResultChain_Receipt_descriptor;
      }

      @Override
      public Receipt getDefaultInstanceForType() {
        return Receipt.getDefaultInstance();
      }

      @Override
      public Receipt build() {
        Receipt result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Receipt buildPartial() {
        Receipt result = new Receipt(this);
        result.recall_ = recall_;
        result.fallback_ = fallback_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }

      @Override
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return super.setField(field, value);
      }

      @Override
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @Override
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @Override
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @Override
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return super.addRepeatedField(field, value);
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Receipt) {
          return mergeFrom((Receipt) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Receipt other) {
        if (other == Receipt.getDefaultInstance()) return this;
        if (other.getRecall() != 0) {
          setRecall(other.getRecall());
        }
        if (!other.getFallback().isEmpty()) {
          fallback_ = other.fallback_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        Receipt parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Receipt) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int recall_;

      /**
       * <code>int32 recall = 1;</code>
       *
       * @return The recall.
       */
      @Override
      public int getRecall() {
        return recall_;
      }

      /**
       * <code>int32 recall = 1;</code>
       *
       * @param value The recall to set.
       * @return This builder for chaining.
       */
      public Builder setRecall(int value) {

        recall_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>int32 recall = 1;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearRecall() {

        recall_ = 0;
        onChanged();
        return this;
      }

      private Object fallback_ = "";

      /**
       * <code>string fallback = 2;</code>
       *
       * @return The fallback.
       */
      public String getFallback() {
        Object ref = fallback_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          fallback_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }

      /**
       * <code>string fallback = 2;</code>
       *
       * @return The bytes for fallback.
       */
      public com.google.protobuf.ByteString
      getFallbackBytes() {
        Object ref = fallback_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          fallback_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string fallback = 2;</code>
       *
       * @param value The fallback to set.
       * @return This builder for chaining.
       */
      public Builder setFallback(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        fallback_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string fallback = 2;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearFallback() {

        fallback_ = getDefaultInstance().getFallback();
        onChanged();
        return this;
      }

      /**
       * <code>string fallback = 2;</code>
       *
       * @param value The bytes for fallback to set.
       * @return This builder for chaining.
       */
      public Builder setFallbackBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        fallback_ = value;
        onChanged();
        return this;
      }

      @Override
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MsgResultChain.Receipt)
    }

    // @@protoc_insertion_point(class_scope:MsgResultChain.Receipt)
    private static final Receipt DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new Receipt();
    }

    public static Receipt getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Receipt>
            PARSER = new com.google.protobuf.AbstractParser<Receipt>() {
      @Override
      public Receipt parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new Receipt(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Receipt> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Receipt> getParserForType() {
      return PARSER;
    }

    @Override
    public Receipt getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int CODE_FIELD_NUMBER = 1;
  private int code_;

  /**
   * <code>.MsgResultChain.Code code = 1;</code>
   *
   * @return The enum numeric value on the wire for code.
   */
  @Override
  public int getCodeValue() {
    return code_;
  }

  /**
   * <code>.MsgResultChain.Code code = 1;</code>
   *
   * @return The code.
   */
  @Override
  public Code getCode() {
    @SuppressWarnings("deprecation")
    Code result = Code.valueOf(code_);
    return result == null ? Code.UNRECOGNIZED : result;
  }

  public static final int MSGRESULT_FIELD_NUMBER = 2;
  private java.util.List<MsgResult> msgResult_;

  /**
   * <code>repeated .MsgResult msgResult = 2;</code>
   */
  @Override
  public java.util.List<MsgResult> getMsgResultList() {
    return msgResult_;
  }

  /**
   * <code>repeated .MsgResult msgResult = 2;</code>
   */
  @Override
  public java.util.List<? extends MsgResultOrBuilder>
  getMsgResultOrBuilderList() {
    return msgResult_;
  }

  /**
   * <code>repeated .MsgResult msgResult = 2;</code>
   */
  @Override
  public int getMsgResultCount() {
    return msgResult_.size();
  }

  /**
   * <code>repeated .MsgResult msgResult = 2;</code>
   */
  @Override
  public MsgResult getMsgResult(int index) {
    return msgResult_.get(index);
  }

  /**
   * <code>repeated .MsgResult msgResult = 2;</code>
   */
  @Override
  public MsgResultOrBuilder getMsgResultOrBuilder(
          int index) {
    return msgResult_.get(index);
  }

  public static final int RECEIPT_FIELD_NUMBER = 3;
  private Receipt receipt_;

  /**
   * <code>.MsgResultChain.Receipt receipt = 3;</code>
   *
   * @return Whether the receipt field is set.
   */
  @Override
  public boolean hasReceipt() {
    return receipt_ != null;
  }

  /**
   * <code>.MsgResultChain.Receipt receipt = 3;</code>
   *
   * @return The receipt.
   */
  @Override
  public Receipt getReceipt() {
    return receipt_ == null ? Receipt.getDefaultInstance() : receipt_;
  }

  /**
   * <code>.MsgResultChain.Receipt receipt = 3;</code>
   */
  @Override
  public ReceiptOrBuilder getReceiptOrBuilder() {
    return getReceipt();
  }

  public static final int META_FIELD_NUMBER = 4;

  private static final class MetaDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
            String, String> defaultEntry =
            com.google.protobuf.MapEntry
                    .<String, String>newDefaultInstance(
                            BaseProto.internal_static_MsgResultChain_MetaEntry_descriptor,
                            com.google.protobuf.WireFormat.FieldType.STRING,
                            "",
                            com.google.protobuf.WireFormat.FieldType.STRING,
                            "");
  }

  private com.google.protobuf.MapField<
          String, String> meta_;

  private com.google.protobuf.MapField<String, String>
  internalGetMeta() {
    if (meta_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
              MetaDefaultEntryHolder.defaultEntry);
    }
    return meta_;
  }

  public int getMetaCount() {
    return internalGetMeta().getMap().size();
  }

  /**
   * <code>map&lt;string, string&gt; meta = 4;</code>
   */

  @Override
  public boolean containsMeta(
          String key) {
    if (key == null) {
      throw new NullPointerException("map key");
    }
    return internalGetMeta().getMap().containsKey(key);
  }

  /**
   * Use {@link #getMetaMap()} instead.
   */
  @Override
  @Deprecated
  public java.util.Map<String, String> getMeta() {
    return getMetaMap();
  }

  /**
   * <code>map&lt;string, string&gt; meta = 4;</code>
   */
  @Override

  public java.util.Map<String, String> getMetaMap() {
    return internalGetMeta().getMap();
  }

  /**
   * <code>map&lt;string, string&gt; meta = 4;</code>
   */
  @Override

  public String getMetaOrDefault(
          String key,
          String defaultValue) {
    if (key == null) {
      throw new NullPointerException("map key");
    }
    java.util.Map<String, String> map =
            internalGetMeta().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }

  /**
   * <code>map&lt;string, string&gt; meta = 4;</code>
   */
  @Override

  public String getMetaOrThrow(
          String key) {
    if (key == null) {
      throw new NullPointerException("map key");
    }
    java.util.Map<String, String> map =
            internalGetMeta().getMap();
    if (!map.containsKey(key)) {
      throw new IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;

  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
          throws java.io.IOException {
    if (code_ != Code.OK.getNumber()) {
      output.writeEnum(1, code_);
    }
    for (int i = 0; i < msgResult_.size(); i++) {
      output.writeMessage(2, msgResult_.get(i));
    }
    if (receipt_ != null) {
      output.writeMessage(3, getReceipt());
    }
    com.google.protobuf.GeneratedMessageV3
            .serializeStringMapTo(
                    output,
                    internalGetMeta(),
                    MetaDefaultEntryHolder.defaultEntry,
                    4);
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (code_ != Code.OK.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
              .computeEnumSize(1, code_);
    }
    for (int i = 0; i < msgResult_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(2, msgResult_.get(i));
    }
    if (receipt_ != null) {
      size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(3, getReceipt());
    }
    for (java.util.Map.Entry<String, String> entry
            : internalGetMeta().getMap().entrySet()) {
      com.google.protobuf.MapEntry<String, String>
              meta__ = MetaDefaultEntryHolder.defaultEntry.newBuilderForType()
              .setKey(entry.getKey())
              .setValue(entry.getValue())
              .build();
      size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(4, meta__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof MsgResultChain)) {
      return super.equals(obj);
    }
    MsgResultChain other = (MsgResultChain) obj;

    if (code_ != other.code_) return false;
    if (!getMsgResultList()
            .equals(other.getMsgResultList())) return false;
    if (hasReceipt() != other.hasReceipt()) return false;
    if (hasReceipt()) {
      if (!getReceipt()
              .equals(other.getReceipt())) return false;
    }
    if (!internalGetMeta().equals(
            other.internalGetMeta())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + code_;
    if (getMsgResultCount() > 0) {
      hash = (37 * hash) + MSGRESULT_FIELD_NUMBER;
      hash = (53 * hash) + getMsgResultList().hashCode();
    }
    if (hasReceipt()) {
      hash = (37 * hash) + RECEIPT_FIELD_NUMBER;
      hash = (53 * hash) + getReceipt().hashCode();
    }
    if (!internalGetMeta().getMap().isEmpty()) {
      hash = (37 * hash) + META_FIELD_NUMBER;
      hash = (53 * hash) + internalGetMeta().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static MsgResultChain parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static MsgResultChain parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static MsgResultChain parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static MsgResultChain parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static MsgResultChain parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static MsgResultChain parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static MsgResultChain parseFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static MsgResultChain parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static MsgResultChain parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
  }

  public static MsgResultChain parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static MsgResultChain parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static MsgResultChain parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(MsgResultChain prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
          BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  /**
   * Protobuf type {@code MsgResultChain}
   */
  public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:MsgResultChain)
          MsgResultChainOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return BaseProto.internal_static_MsgResultChain_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
            int number) {
      switch (number) {
        case 4:
          return internalGetMeta();
        default:
          throw new RuntimeException(
                  "Invalid map field number: " + number);
      }
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
            int number) {
      switch (number) {
        case 4:
          return internalGetMutableMeta();
        default:
          throw new RuntimeException(
                  "Invalid map field number: " + number);
      }
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
      return BaseProto.internal_static_MsgResultChain_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      MsgResultChain.class, Builder.class);
    }

    // Construct using io.net.api.MsgResultChain.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
            BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMsgResultFieldBuilder();
      }
    }

    @Override
    public Builder clear() {
      super.clear();
      code_ = 0;

      if (msgResultBuilder_ == null) {
        msgResult_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        msgResultBuilder_.clear();
      }
      if (receiptBuilder_ == null) {
        receipt_ = null;
      } else {
        receipt_ = null;
        receiptBuilder_ = null;
      }
      internalGetMutableMeta().clear();
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return BaseProto.internal_static_MsgResultChain_descriptor;
    }

    @Override
    public MsgResultChain getDefaultInstanceForType() {
      return MsgResultChain.getDefaultInstance();
    }

    @Override
    public MsgResultChain build() {
      MsgResultChain result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public MsgResultChain buildPartial() {
      MsgResultChain result = new MsgResultChain(this);
      int from_bitField0_ = bitField0_;
      result.code_ = code_;
      if (msgResultBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          msgResult_ = java.util.Collections.unmodifiableList(msgResult_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.msgResult_ = msgResult_;
      } else {
        result.msgResult_ = msgResultBuilder_.build();
      }
      if (receiptBuilder_ == null) {
        result.receipt_ = receipt_;
      } else {
        result.receipt_ = receiptBuilder_.build();
      }
      result.meta_ = internalGetMeta();
      result.meta_.makeImmutable();
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }

    @Override
    public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
      return super.setField(field, value);
    }

    @Override
    public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @Override
    public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @Override
    public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @Override
    public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
      return super.addRepeatedField(field, value);
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof MsgResultChain) {
        return mergeFrom((MsgResultChain) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(MsgResultChain other) {
      if (other == MsgResultChain.getDefaultInstance()) return this;
      if (other.code_ != 0) {
        setCodeValue(other.getCodeValue());
      }
      if (msgResultBuilder_ == null) {
        if (!other.msgResult_.isEmpty()) {
          if (msgResult_.isEmpty()) {
            msgResult_ = other.msgResult_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMsgResultIsMutable();
            msgResult_.addAll(other.msgResult_);
          }
          onChanged();
        }
      } else {
        if (!other.msgResult_.isEmpty()) {
          if (msgResultBuilder_.isEmpty()) {
            msgResultBuilder_.dispose();
            msgResultBuilder_ = null;
            msgResult_ = other.msgResult_;
            bitField0_ = (bitField0_ & ~0x00000001);
            msgResultBuilder_ =
                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                            getMsgResultFieldBuilder() : null;
          } else {
            msgResultBuilder_.addAllMessages(other.msgResult_);
          }
        }
      }
      if (other.hasReceipt()) {
        mergeReceipt(other.getReceipt());
      }
      internalGetMutableMeta().mergeFrom(
              other.internalGetMeta());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      MsgResultChain parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (MsgResultChain) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int bitField0_;

    private int code_ = 0;

    /**
     * <code>.MsgResultChain.Code code = 1;</code>
     *
     * @return The enum numeric value on the wire for code.
     */
    @Override
    public int getCodeValue() {
      return code_;
    }

    /**
     * <code>.MsgResultChain.Code code = 1;</code>
     *
     * @param value The enum numeric value on the wire for code to set.
     * @return This builder for chaining.
     */
    public Builder setCodeValue(int value) {

      code_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>.MsgResultChain.Code code = 1;</code>
     *
     * @return The code.
     */
    @Override
    public Code getCode() {
      @SuppressWarnings("deprecation")
      Code result = Code.valueOf(code_);
      return result == null ? Code.UNRECOGNIZED : result;
    }

    /**
     * <code>.MsgResultChain.Code code = 1;</code>
     *
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(Code value) {
      if (value == null) {
        throw new NullPointerException();
      }

      code_ = value.getNumber();
      onChanged();
      return this;
    }

    /**
     * <code>.MsgResultChain.Code code = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearCode() {

      code_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<MsgResult> msgResult_ =
            java.util.Collections.emptyList();

    private void ensureMsgResultIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        msgResult_ = new java.util.ArrayList<MsgResult>(msgResult_);
        bitField0_ |= 0x00000001;
      }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            MsgResult, MsgResult.Builder, MsgResultOrBuilder> msgResultBuilder_;

    /**
     * <code>repeated .MsgResult msgResult = 2;</code>
     */
    public java.util.List<MsgResult> getMsgResultList() {
      if (msgResultBuilder_ == null) {
        return java.util.Collections.unmodifiableList(msgResult_);
      } else {
        return msgResultBuilder_.getMessageList();
      }
    }

    /**
     * <code>repeated .MsgResult msgResult = 2;</code>
     */
    public int getMsgResultCount() {
      if (msgResultBuilder_ == null) {
        return msgResult_.size();
      } else {
        return msgResultBuilder_.getCount();
      }
    }

    /**
     * <code>repeated .MsgResult msgResult = 2;</code>
     */
    public MsgResult getMsgResult(int index) {
      if (msgResultBuilder_ == null) {
        return msgResult_.get(index);
      } else {
        return msgResultBuilder_.getMessage(index);
      }
    }

    /**
     * <code>repeated .MsgResult msgResult = 2;</code>
     */
    public Builder setMsgResult(
            int index, MsgResult value) {
      if (msgResultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMsgResultIsMutable();
        msgResult_.set(index, value);
        onChanged();
      } else {
        msgResultBuilder_.setMessage(index, value);
      }
      return this;
    }

    /**
     * <code>repeated .MsgResult msgResult = 2;</code>
     */
    public Builder setMsgResult(
            int index, MsgResult.Builder builderForValue) {
      if (msgResultBuilder_ == null) {
        ensureMsgResultIsMutable();
        msgResult_.set(index, builderForValue.build());
        onChanged();
      } else {
        msgResultBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .MsgResult msgResult = 2;</code>
     */
    public Builder addMsgResult(MsgResult value) {
      if (msgResultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMsgResultIsMutable();
        msgResult_.add(value);
        onChanged();
      } else {
        msgResultBuilder_.addMessage(value);
      }
      return this;
    }

    /**
     * <code>repeated .MsgResult msgResult = 2;</code>
     */
    public Builder addMsgResult(
            int index, MsgResult value) {
      if (msgResultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMsgResultIsMutable();
        msgResult_.add(index, value);
        onChanged();
      } else {
        msgResultBuilder_.addMessage(index, value);
      }
      return this;
    }

    /**
     * <code>repeated .MsgResult msgResult = 2;</code>
     */
    public Builder addMsgResult(
            MsgResult.Builder builderForValue) {
      if (msgResultBuilder_ == null) {
        ensureMsgResultIsMutable();
        msgResult_.add(builderForValue.build());
        onChanged();
      } else {
        msgResultBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .MsgResult msgResult = 2;</code>
     */
    public Builder addMsgResult(
            int index, MsgResult.Builder builderForValue) {
      if (msgResultBuilder_ == null) {
        ensureMsgResultIsMutable();
        msgResult_.add(index, builderForValue.build());
        onChanged();
      } else {
        msgResultBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .MsgResult msgResult = 2;</code>
     */
    public Builder addAllMsgResult(
            Iterable<? extends MsgResult> values) {
      if (msgResultBuilder_ == null) {
        ensureMsgResultIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, msgResult_);
        onChanged();
      } else {
        msgResultBuilder_.addAllMessages(values);
      }
      return this;
    }

    /**
     * <code>repeated .MsgResult msgResult = 2;</code>
     */
    public Builder clearMsgResult() {
      if (msgResultBuilder_ == null) {
        msgResult_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        msgResultBuilder_.clear();
      }
      return this;
    }

    /**
     * <code>repeated .MsgResult msgResult = 2;</code>
     */
    public Builder removeMsgResult(int index) {
      if (msgResultBuilder_ == null) {
        ensureMsgResultIsMutable();
        msgResult_.remove(index);
        onChanged();
      } else {
        msgResultBuilder_.remove(index);
      }
      return this;
    }

    /**
     * <code>repeated .MsgResult msgResult = 2;</code>
     */
    public MsgResult.Builder getMsgResultBuilder(
            int index) {
      return getMsgResultFieldBuilder().getBuilder(index);
    }

    /**
     * <code>repeated .MsgResult msgResult = 2;</code>
     */
    public MsgResultOrBuilder getMsgResultOrBuilder(
            int index) {
      if (msgResultBuilder_ == null) {
        return msgResult_.get(index);
      } else {
        return msgResultBuilder_.getMessageOrBuilder(index);
      }
    }

    /**
     * <code>repeated .MsgResult msgResult = 2;</code>
     */
    public java.util.List<? extends MsgResultOrBuilder>
    getMsgResultOrBuilderList() {
      if (msgResultBuilder_ != null) {
        return msgResultBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(msgResult_);
      }
    }

    /**
     * <code>repeated .MsgResult msgResult = 2;</code>
     */
    public MsgResult.Builder addMsgResultBuilder() {
      return getMsgResultFieldBuilder().addBuilder(
              MsgResult.getDefaultInstance());
    }

    /**
     * <code>repeated .MsgResult msgResult = 2;</code>
     */
    public MsgResult.Builder addMsgResultBuilder(
            int index) {
      return getMsgResultFieldBuilder().addBuilder(
              index, MsgResult.getDefaultInstance());
    }

    /**
     * <code>repeated .MsgResult msgResult = 2;</code>
     */
    public java.util.List<MsgResult.Builder>
    getMsgResultBuilderList() {
      return getMsgResultFieldBuilder().getBuilderList();
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            MsgResult, MsgResult.Builder, MsgResultOrBuilder>
    getMsgResultFieldBuilder() {
      if (msgResultBuilder_ == null) {
        msgResultBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                MsgResult, MsgResult.Builder, MsgResultOrBuilder>(
                msgResult_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        msgResult_ = null;
      }
      return msgResultBuilder_;
    }

    private Receipt receipt_;
    private com.google.protobuf.SingleFieldBuilderV3<
            Receipt, Receipt.Builder, ReceiptOrBuilder> receiptBuilder_;

    /**
     * <code>.MsgResultChain.Receipt receipt = 3;</code>
     *
     * @return Whether the receipt field is set.
     */
    public boolean hasReceipt() {
      return receiptBuilder_ != null || receipt_ != null;
    }

    /**
     * <code>.MsgResultChain.Receipt receipt = 3;</code>
     *
     * @return The receipt.
     */
    public Receipt getReceipt() {
      if (receiptBuilder_ == null) {
        return receipt_ == null ? Receipt.getDefaultInstance() : receipt_;
      } else {
        return receiptBuilder_.getMessage();
      }
    }

    /**
     * <code>.MsgResultChain.Receipt receipt = 3;</code>
     */
    public Builder setReceipt(Receipt value) {
      if (receiptBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        receipt_ = value;
        onChanged();
      } else {
        receiptBuilder_.setMessage(value);
      }

      return this;
    }

    /**
     * <code>.MsgResultChain.Receipt receipt = 3;</code>
     */
    public Builder setReceipt(
            Receipt.Builder builderForValue) {
      if (receiptBuilder_ == null) {
        receipt_ = builderForValue.build();
        onChanged();
      } else {
        receiptBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }

    /**
     * <code>.MsgResultChain.Receipt receipt = 3;</code>
     */
    public Builder mergeReceipt(Receipt value) {
      if (receiptBuilder_ == null) {
        if (receipt_ != null) {
          receipt_ =
                  Receipt.newBuilder(receipt_).mergeFrom(value).buildPartial();
        } else {
          receipt_ = value;
        }
        onChanged();
      } else {
        receiptBuilder_.mergeFrom(value);
      }

      return this;
    }

    /**
     * <code>.MsgResultChain.Receipt receipt = 3;</code>
     */
    public Builder clearReceipt() {
      if (receiptBuilder_ == null) {
        receipt_ = null;
        onChanged();
      } else {
        receipt_ = null;
        receiptBuilder_ = null;
      }

      return this;
    }

    /**
     * <code>.MsgResultChain.Receipt receipt = 3;</code>
     */
    public Receipt.Builder getReceiptBuilder() {

      onChanged();
      return getReceiptFieldBuilder().getBuilder();
    }

    /**
     * <code>.MsgResultChain.Receipt receipt = 3;</code>
     */
    public ReceiptOrBuilder getReceiptOrBuilder() {
      if (receiptBuilder_ != null) {
        return receiptBuilder_.getMessageOrBuilder();
      } else {
        return receipt_ == null ?
                Receipt.getDefaultInstance() : receipt_;
      }
    }

    /**
     * <code>.MsgResultChain.Receipt receipt = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            Receipt, Receipt.Builder, ReceiptOrBuilder>
    getReceiptFieldBuilder() {
      if (receiptBuilder_ == null) {
        receiptBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                Receipt, Receipt.Builder, ReceiptOrBuilder>(
                getReceipt(),
                getParentForChildren(),
                isClean());
        receipt_ = null;
      }
      return receiptBuilder_;
    }

    private com.google.protobuf.MapField<
            String, String> meta_;

    private com.google.protobuf.MapField<String, String>
    internalGetMeta() {
      if (meta_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
                MetaDefaultEntryHolder.defaultEntry);
      }
      return meta_;
    }

    private com.google.protobuf.MapField<String, String>
    internalGetMutableMeta() {
      onChanged();
      ;
      if (meta_ == null) {
        meta_ = com.google.protobuf.MapField.newMapField(
                MetaDefaultEntryHolder.defaultEntry);
      }
      if (!meta_.isMutable()) {
        meta_ = meta_.copy();
      }
      return meta_;
    }

    public int getMetaCount() {
      return internalGetMeta().getMap().size();
    }

    /**
     * <code>map&lt;string, string&gt; meta = 4;</code>
     */

    @Override
    public boolean containsMeta(
            String key) {
      if (key == null) {
        throw new NullPointerException("map key");
      }
      return internalGetMeta().getMap().containsKey(key);
    }

    /**
     * Use {@link #getMetaMap()} instead.
     */
    @Override
    @Deprecated
    public java.util.Map<String, String> getMeta() {
      return getMetaMap();
    }

    /**
     * <code>map&lt;string, string&gt; meta = 4;</code>
     */
    @Override

    public java.util.Map<String, String> getMetaMap() {
      return internalGetMeta().getMap();
    }

    /**
     * <code>map&lt;string, string&gt; meta = 4;</code>
     */
    @Override

    public String getMetaOrDefault(
            String key,
            String defaultValue) {
      if (key == null) {
        throw new NullPointerException("map key");
      }
      java.util.Map<String, String> map =
              internalGetMeta().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }

    /**
     * <code>map&lt;string, string&gt; meta = 4;</code>
     */
    @Override

    public String getMetaOrThrow(
            String key) {
      if (key == null) {
        throw new NullPointerException("map key");
      }
      java.util.Map<String, String> map =
              internalGetMeta().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearMeta() {
      internalGetMutableMeta().getMutableMap()
              .clear();
      return this;
    }

    /**
     * <code>map&lt;string, string&gt; meta = 4;</code>
     */

    public Builder removeMeta(
            String key) {
      if (key == null) {
        throw new NullPointerException("map key");
      }
      internalGetMutableMeta().getMutableMap()
              .remove(key);
      return this;
    }

    /**
     * Use alternate mutation accessors instead.
     */
    @Deprecated
    public java.util.Map<String, String>
    getMutableMeta() {
      return internalGetMutableMeta().getMutableMap();
    }

    /**
     * <code>map&lt;string, string&gt; meta = 4;</code>
     */
    public Builder putMeta(
            String key,
            String value) {
      if (key == null) {
        throw new NullPointerException("map key");
      }
      if (value == null) {
        throw new NullPointerException("map value");
      }

      internalGetMutableMeta().getMutableMap()
              .put(key, value);
      return this;
    }

    /**
     * <code>map&lt;string, string&gt; meta = 4;</code>
     */

    public Builder putAllMeta(
            java.util.Map<String, String> values) {
      internalGetMutableMeta().getMutableMap()
              .putAll(values);
      return this;
    }

    @Override
    public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MsgResultChain)
  }

  // @@protoc_insertion_point(class_scope:MsgResultChain)
  private static final MsgResultChain DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new MsgResultChain();
  }

  public static MsgResultChain getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MsgResultChain>
          PARSER = new com.google.protobuf.AbstractParser<MsgResultChain>() {
    @Override
    public MsgResultChain parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return new MsgResultChain(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MsgResultChain> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<MsgResultChain> getParserForType() {
    return PARSER;
  }

  @Override
  public MsgResultChain getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

