// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

package io.net.api;

public interface MsgResultChainOrBuilder extends
        // @@protoc_insertion_point(interface_extends:MsgResultChain)
        com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.MsgResultChain.Code code = 1;</code>
   *
   * @return The enum numeric value on the wire for code.
   */
  int getCodeValue();

  /**
   * <code>.MsgResultChain.Code code = 1;</code>
   *
   * @return The code.
   */
  MsgResultChain.Code getCode();

  /**
   * <code>repeated .MsgResult msgResult = 2;</code>
   */
  java.util.List<MsgResult>
  getMsgResultList();

  /**
   * <code>repeated .MsgResult msgResult = 2;</code>
   */
  MsgResult getMsgResult(int index);

  /**
   * <code>repeated .MsgResult msgResult = 2;</code>
   */
  int getMsgResultCount();

  /**
   * <code>repeated .MsgResult msgResult = 2;</code>
   */
  java.util.List<? extends MsgResultOrBuilder>
  getMsgResultOrBuilderList();

  /**
   * <code>repeated .MsgResult msgResult = 2;</code>
   */
  MsgResultOrBuilder getMsgResultOrBuilder(
          int index);

  /**
   * <code>.MsgResultChain.Receipt receipt = 3;</code>
   *
   * @return Whether the receipt field is set.
   */
  boolean hasReceipt();

  /**
   * <code>.MsgResultChain.Receipt receipt = 3;</code>
   *
   * @return The receipt.
   */
  MsgResultChain.Receipt getReceipt();

  /**
   * <code>.MsgResultChain.Receipt receipt = 3;</code>
   */
  MsgResultChain.ReceiptOrBuilder getReceiptOrBuilder();

  /**
   * <code>map&lt;string, string&gt; meta = 4;</code>
   */
  int getMetaCount();

  /**
   * <code>map&lt;string, string&gt; meta = 4;</code>
   */
  boolean containsMeta(
          String key);

  /**
   * Use {@link #getMetaMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getMeta();

  /**
   * <code>map&lt;string, string&gt; meta = 4;</code>
   */
  java.util.Map<String, String>
  getMetaMap();

  /**
   * <code>map&lt;string, string&gt; meta = 4;</code>
   */

  String getMetaOrDefault(
          String key,
          String defaultValue);

  /**
   * <code>map&lt;string, string&gt; meta = 4;</code>
   */

  String getMetaOrThrow(
          String key);
}
